// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, port;

  express = require('express');

  app = express();

  app.use(express["static"](__dirname + '/public'));

  app.get('*', function(req, res) {
    return res.sendfile(__dirname + '/public/index.html');
  });

  port = process.env.PORT || process.argv[2] || 3000;

  app.listen(port);

  console.log('Listening on port ' + port + '.');

}).call(this);
